version: '3.8'

services:
  workout-tracker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: workout-tracker-prod
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_PATH=/app/data/workout_tracker.db
    env_file:
      - .env
    volumes:
      # Persist database data
      - workout_data:/app/data
      # Optional: mount backup location
      - ./backups:/app/backups:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - workout-net

  # Optional: Add a reverse proxy (uncomment if needed)
  # nginx:
  #   image: nginx:alpine
  #   container_name: workout-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - workout-tracker
  #   networks:
  #     - workout-net

volumes:
  workout_data:
    driver: local

networks:
  workout-net:
    driver: bridge
